/**
 * HKTC_PRD_DAILY_PRO_PLAN_ARRグリッド定義
 */

let HktcPrdDailyProPlanArrGridColumns = [
    Column.cell('PRO_NO', Messages['HktcPrdDailyProPlanArrGrid.proNo'], 140, 'primaryKey', null),
    Column.text('CHILD_PLAN_NO', Messages['HktcPrdDailyProPlanArrGrid.childPlanNo'], 120, '', null),
    Column.text('ROUTING', Messages['HktcPrdDailyProPlanArrGrid.routing'], 20, '', null),
    Column.refer('WC_CODE', Messages['HktcPrdDailyProPlanArrGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.text('OPE_DETAIL', Messages['HktcPrdDailyProPlanArrGrid.opeDetail'], 100, '', null),
    Column.select('MAC_LOAD_KBN', Messages['HktcPrdDailyProPlanArrGrid.macLoadKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('HUM_PRE_TIME', Messages['HktcPrdDailyProPlanArrGrid.humPreTime'], 70, '', null),
    Column.text('HUM_ACT_TIME', Messages['HktcPrdDailyProPlanArrGrid.humActTime'], 70, '', null),
    Column.text('MAC_PRE_TIME', Messages['HktcPrdDailyProPlanArrGrid.macPreTime'], 70, '', null),
    Column.text('MAC_ACT_TIME', Messages['HktcPrdDailyProPlanArrGrid.macActTime'], 70, '', null),
    Column.text('COMMENT1', Messages['HktcPrdDailyProPlanArrGrid.comment1'], 300, '', null),
    Column.text('COMMENT2', Messages['HktcPrdDailyProPlanArrGrid.comment2'], 300, '', null),
    Column.text('UNIT_WEIGHT', Messages['HktcPrdDailyProPlanArrGrid.unitWeight'], 110, '', null),
    Column.check('NECK_FLAG', Messages['HktcPrdDailyProPlanArrGrid.neckFlag'], 10, ''),
    Column.text('NEXT_ROUT_PRO_NO', Messages['HktcPrdDailyProPlanArrGrid.nextRoutProNo'], 140, '', null),
    Column.date('INITIAL_BEG_DATE', Messages['HktcPrdDailyProPlanArrGrid.initialBegDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('INITIAL_END_DATE', Messages['HktcPrdDailyProPlanArrGrid.initialEndDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('BEG_DATE', Messages['HktcPrdDailyProPlanArrGrid.begDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('END_DATE', Messages['HktcPrdDailyProPlanArrGrid.endDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('START_DATE', Messages['HktcPrdDailyProPlanArrGrid.startDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('COMP_DATE', Messages['HktcPrdDailyProPlanArrGrid.compDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.refer('OPE_WC_CODE', Messages['HktcPrdDailyProPlanArrGrid.opeWcCode'], 30, '', 'OPE_WC_NAME'),
    Column.text('PRO_STATUS', Messages['HktcPrdDailyProPlanArrGrid.proStatus'], 10, '', null),
    Column.date('DEL_CAN_DATE', Messages['HktcPrdDailyProPlanArrGrid.delCanDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.check('EXP_FLAG', Messages['HktcPrdDailyProPlanArrGrid.expFlag'], 10, ''),
    Column.check('VISIBLE_FLAG', Messages['HktcPrdDailyProPlanArrGrid.visibleFlag'], 10, ''),
    Column.check('SUP_FLAG', Messages['HktcPrdDailyProPlanArrGrid.supFlag'], 10, ''),
    Column.text('SHORT_NO', Messages['HktcPrdDailyProPlanArrGrid.shortNo'], 70, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['HktcPrdDailyProPlanArrGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['HktcPrdDailyProPlanArrGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['HktcPrdDailyProPlanArrGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['HktcPrdDailyProPlanArrGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('DELETE_FLAG', Messages['HktcPrdDailyProPlanArrGrid.deleteFlag'], 10, ''),
    Column.check('NYUKO_FLAG', Messages['HktcPrdDailyProPlanArrGrid.nyukoFlag'], 20, ''),
    Column.text('GOOD_COUNTS', Messages['HktcPrdDailyProPlanArrGrid.goodCounts'], 60, '', null),
];
