/**
 * MFG_OBSERVANCE_RATE_OUTグリッド定義
 */

let MfgObservanceRateOutGridColumns = [
    Column.cell('YYYY', Messages['MfgObservanceRateOutGrid.yyyy'], 40, 'primaryKey', null),
    Column.cell('MM', Messages['MfgObservanceRateOutGrid.mm'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MfgObservanceRateOutGrid.wcCode'], 30, 'primaryKey', 'WC_NAME'),
    Column.text('OBSERVANCE_RATE', Messages['MfgObservanceRateOutGrid.observanceRate'], 50, '', null),
    Column.text('LATE_M5OVER', Messages['MfgObservanceRateOutGrid.lateM5over'], 40, '', null),
    Column.text('LATE_M5', Messages['MfgObservanceRateOutGrid.lateM5'], 40, '', null),
    Column.text('LATE_M4', Messages['MfgObservanceRateOutGrid.lateM4'], 40, '', null),
    Column.text('LATE_M3', Messages['MfgObservanceRateOutGrid.lateM3'], 40, '', null),
    Column.text('LATE_M2', Messages['MfgObservanceRateOutGrid.lateM2'], 40, '', null),
    Column.text('LATE_M1', Messages['MfgObservanceRateOutGrid.lateM1'], 40, '', null),
    Column.text('LATE_0', Messages['MfgObservanceRateOutGrid.late0'], 40, '', null),
    Column.text('LATE_P1', Messages['MfgObservanceRateOutGrid.lateP1'], 40, '', null),
    Column.text('LATE_P2', Messages['MfgObservanceRateOutGrid.lateP2'], 40, '', null),
    Column.text('LATE_P3', Messages['MfgObservanceRateOutGrid.lateP3'], 40, '', null),
    Column.text('LATE_P4', Messages['MfgObservanceRateOutGrid.lateP4'], 40, '', null),
    Column.text('LATE_P5', Messages['MfgObservanceRateOutGrid.lateP5'], 40, '', null),
    Column.text('LATE_P6', Messages['MfgObservanceRateOutGrid.lateP6'], 40, '', null),
    Column.text('LATE_P7', Messages['MfgObservanceRateOutGrid.lateP7'], 40, '', null),
    Column.text('LATE_P8', Messages['MfgObservanceRateOutGrid.lateP8'], 40, '', null),
    Column.text('LATE_P9', Messages['MfgObservanceRateOutGrid.lateP9'], 40, '', null),
    Column.text('LATE_P10', Messages['MfgObservanceRateOutGrid.lateP10'], 40, '', null),
    Column.text('LATE_P11', Messages['MfgObservanceRateOutGrid.lateP11'], 40, '', null),
    Column.text('LATE_P12', Messages['MfgObservanceRateOutGrid.lateP12'], 40, '', null),
    Column.text('LATE_P13', Messages['MfgObservanceRateOutGrid.lateP13'], 40, '', null),
    Column.text('LATE_P14', Messages['MfgObservanceRateOutGrid.lateP14'], 40, '', null),
    Column.text('LATE_P15', Messages['MfgObservanceRateOutGrid.lateP15'], 40, '', null),
    Column.text('LATE_P16', Messages['MfgObservanceRateOutGrid.lateP16'], 40, '', null),
    Column.text('LATE_P17', Messages['MfgObservanceRateOutGrid.lateP17'], 40, '', null),
    Column.text('LATE_P18', Messages['MfgObservanceRateOutGrid.lateP18'], 40, '', null),
    Column.text('LATE_P19', Messages['MfgObservanceRateOutGrid.lateP19'], 40, '', null),
    Column.text('LATE_P20', Messages['MfgObservanceRateOutGrid.lateP20'], 40, '', null),
    Column.text('LATE_P20OVER', Messages['MfgObservanceRateOutGrid.lateP20over'], 40, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MfgObservanceRateOutGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MfgObservanceRateOutGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MfgObservanceRateOutGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MfgObservanceRateOutGrid.userIdChange'], 100, 'metaInfo', null),
];
