/**
 * MFG_OBSERVANCE_RATE_INグリッド定義
 */

let MfgObservanceRateInGridColumns = [
    Column.cell('YYYY', Messages['MfgObservanceRateInGrid.yyyy'], 40, 'primaryKey', null),
    Column.cell('MM', Messages['MfgObservanceRateInGrid.mm'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MfgObservanceRateInGrid.wcCode'], 30, 'primaryKey', 'WC_NAME'),
    Column.text('OBSERVANCE_RATE', Messages['MfgObservanceRateInGrid.observanceRate'], 50, '', null),
    Column.text('LATE_M5OVER', Messages['MfgObservanceRateInGrid.lateM5over'], 40, '', null),
    Column.text('LATE_M5', Messages['MfgObservanceRateInGrid.lateM5'], 40, '', null),
    Column.text('LATE_M4', Messages['MfgObservanceRateInGrid.lateM4'], 40, '', null),
    Column.text('LATE_M3', Messages['MfgObservanceRateInGrid.lateM3'], 40, '', null),
    Column.text('LATE_M2', Messages['MfgObservanceRateInGrid.lateM2'], 40, '', null),
    Column.text('LATE_M1', Messages['MfgObservanceRateInGrid.lateM1'], 40, '', null),
    Column.text('LATE_0', Messages['MfgObservanceRateInGrid.late0'], 40, '', null),
    Column.text('LATE_P1', Messages['MfgObservanceRateInGrid.lateP1'], 40, '', null),
    Column.text('LATE_P2', Messages['MfgObservanceRateInGrid.lateP2'], 40, '', null),
    Column.text('LATE_P3', Messages['MfgObservanceRateInGrid.lateP3'], 40, '', null),
    Column.text('LATE_P4', Messages['MfgObservanceRateInGrid.lateP4'], 40, '', null),
    Column.text('LATE_P5', Messages['MfgObservanceRateInGrid.lateP5'], 40, '', null),
    Column.text('LATE_P6', Messages['MfgObservanceRateInGrid.lateP6'], 40, '', null),
    Column.text('LATE_P7', Messages['MfgObservanceRateInGrid.lateP7'], 40, '', null),
    Column.text('LATE_P8', Messages['MfgObservanceRateInGrid.lateP8'], 40, '', null),
    Column.text('LATE_P9', Messages['MfgObservanceRateInGrid.lateP9'], 40, '', null),
    Column.text('LATE_P10', Messages['MfgObservanceRateInGrid.lateP10'], 40, '', null),
    Column.text('LATE_P11', Messages['MfgObservanceRateInGrid.lateP11'], 40, '', null),
    Column.text('LATE_P12', Messages['MfgObservanceRateInGrid.lateP12'], 40, '', null),
    Column.text('LATE_P13', Messages['MfgObservanceRateInGrid.lateP13'], 40, '', null),
    Column.text('LATE_P14', Messages['MfgObservanceRateInGrid.lateP14'], 40, '', null),
    Column.text('LATE_P15', Messages['MfgObservanceRateInGrid.lateP15'], 40, '', null),
    Column.text('LATE_P16', Messages['MfgObservanceRateInGrid.lateP16'], 40, '', null),
    Column.text('LATE_P17', Messages['MfgObservanceRateInGrid.lateP17'], 40, '', null),
    Column.text('LATE_P18', Messages['MfgObservanceRateInGrid.lateP18'], 40, '', null),
    Column.text('LATE_P19', Messages['MfgObservanceRateInGrid.lateP19'], 40, '', null),
    Column.text('LATE_P20', Messages['MfgObservanceRateInGrid.lateP20'], 40, '', null),
    Column.text('LATE_P20OVER', Messages['MfgObservanceRateInGrid.lateP20over'], 40, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MfgObservanceRateInGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MfgObservanceRateInGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MfgObservanceRateInGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MfgObservanceRateInGrid.userIdChange'], 100, 'metaInfo', null),
];
