/**
 * MFG_TOTAL_RESULT_Qグリッド定義
 */

let MfgTotalResultQGridColumns = [
    Column.cell('RESULT_DATE', Messages['MfgTotalResultQGrid.resultDate'], 60, 'primaryKey', null),
    Column.cell('PRO_GROUP_NO', Messages['MfgTotalResultQGrid.proGroupNo'], 20, 'primaryKey', null),
    Column.cell('HINBAN', Messages['MfgTotalResultQGrid.hinban'], 250, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MfgTotalResultQGrid.routing'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MfgTotalResultQGrid.wcCode'], 30, 'primaryKey', 'WC_NAME'),
    Column.cell('OPE_DETAIL', Messages['MfgTotalResultQGrid.opeDetail'], 100, 'primaryKey', null),
    Column.text('HUM_PRE_TIME', Messages['MfgTotalResultQGrid.humPreTime'], 80, '', null),
    Column.text('HUM_ACT_TIME', Messages['MfgTotalResultQGrid.humActTime'], 80, '', null),
    Column.text('MAC_PRE_TIME', Messages['MfgTotalResultQGrid.macPreTime'], 80, '', null),
    Column.text('MAC_ACT_TIME', Messages['MfgTotalResultQGrid.macActTime'], 80, '', null),
    Column.text('GOOD_COUNTS', Messages['MfgTotalResultQGrid.goodCounts'], 60, '', null),
    Column.text('REJECT_COUNTS', Messages['MfgTotalResultQGrid.rejectCounts'], 60, '', null),
    Column.refer('UNIT_CODE', Messages['MfgTotalResultQGrid.unitCode'], 20, '', 'UNIT_NAME'),
    Column.text('ACT_LT', Messages['MfgTotalResultQGrid.actLt'], 80, '', null),
    Column.text('ACT_WAIT_TIME', Messages['MfgTotalResultQGrid.actWaitTime'], 80, '', null),
    Column.text('EXP_WAIT_TIME', Messages['MfgTotalResultQGrid.expWaitTime'], 80, '', null),
    Column.text('EXP_PRE_TIME', Messages['MfgTotalResultQGrid.expPreTime'], 80, '', null),
    Column.text('EXP_PRO_TIME', Messages['MfgTotalResultQGrid.expProTime'], 80, '', null),
    Column.text('EXP_REST_TIME', Messages['MfgTotalResultQGrid.expRestTime'], 80, '', null),
    Column.text('EXP_CHOKO_TIME', Messages['MfgTotalResultQGrid.expChokoTime'], 80, '', null),
    Column.text('EXP_TROUB_TIME', Messages['MfgTotalResultQGrid.expTroubTime'], 80, '', null),
    Column.text('EXP_SELF_MOD_TIME', Messages['MfgTotalResultQGrid.expSelfModTime'], 80, '', null),
    Column.text('EXP_OTHR_MOD_TIME', Messages['MfgTotalResultQGrid.expOthrModTime'], 80, '', null),
    Column.text('EXP_ETC_TIME', Messages['MfgTotalResultQGrid.expEtcTime'], 80, '', null),
    Column.text('VOLUME_WEIGHT', Messages['MfgTotalResultQGrid.volumeWeight'], 110, '', null),
    Column.text('UNIT_WEIGHT', Messages['MfgTotalResultQGrid.unitWeight'], 110, '', null),
    Column.text('END_MATERIAL_WEIGHT', Messages['MfgTotalResultQGrid.endMaterialWeight'], 110, '', null),
    Column.text('PRO_COUNTS', Messages['MfgTotalResultQGrid.proCounts'], 30, '', null),
    Column.text('LAST_ROUTING', Messages['MfgTotalResultQGrid.lastRouting'], 10, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MfgTotalResultQGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MfgTotalResultQGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MfgTotalResultQGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MfgTotalResultQGrid.userIdChange'], 100, 'metaInfo', null),
];
