/**
 * MFG_TOTAL_COST_REG_LINE_Iグリッド定義
 */

let MfgTotalCostRegLineIGridColumns = [
    Column.cell('YY', Messages['MfgTotalCostRegLineIGrid.yy'], 40, 'primaryKey', null),
    Column.cell('MM', Messages['MfgTotalCostRegLineIGrid.mm'], 20, 'primaryKey', null),
    Column.cell('PRO_GROUP_NO', Messages['MfgTotalCostRegLineIGrid.proGroupNo'], 20, 'primaryKey', null),
    Column.cell('HINBAN', Messages['MfgTotalCostRegLineIGrid.hinban'], 250, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MfgTotalCostRegLineIGrid.routing'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MfgTotalCostRegLineIGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.refer('SUP_CODE', Messages['MfgTotalCostRegLineIGrid.supCode'], 60, '', 'SUP_NAME'),
    Column.text('OPE_DETAIL', Messages['MfgTotalCostRegLineIGrid.opeDetail'], 100, '', null),
    Column.select('LAST_ROUTING_KBN', Messages['MfgTotalCostRegLineIGrid.lastRoutingKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('TOTAL_COST_TARGET_FLAG', Messages['MfgTotalCostRegLineIGrid.totalCostTargetFlag'], 10, ''),
    Column.select('COST_RATE_KBN', Messages['MfgTotalCostRegLineIGrid.costRateKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('UNIT_COST_FIRST', Messages['MfgTotalCostRegLineIGrid.unitCostFirst'], 90, '', null),
    Column.text('UNIT_COST_SECOND', Messages['MfgTotalCostRegLineIGrid.unitCostSecond'], 90, '', null),
    Column.text('TOTAL_UNIT_COST', Messages['MfgTotalCostRegLineIGrid.totalUnitCost'], 90, '', null),
    Column.text('SUM_COST_FIRST', Messages['MfgTotalCostRegLineIGrid.sumCostFirst'], 90, '', null),
    Column.text('SUM_COST_SECOND', Messages['MfgTotalCostRegLineIGrid.sumCostSecond'], 90, '', null),
    Column.text('TOTAL_SUM_COST', Messages['MfgTotalCostRegLineIGrid.totalSumCost'], 90, '', null),
    Column.text('OPE_COUNTS', Messages['MfgTotalCostRegLineIGrid.opeCounts'], 50, '', null),
    Column.text('OPE_AMOUNTS', Messages['MfgTotalCostRegLineIGrid.opeAmounts'], 120, '', null),
    Column.text('UNIT_WEIGHT', Messages['MfgTotalCostRegLineIGrid.unitWeight'], 110, '', null),
    Column.text('OPE_TIME', Messages['MfgTotalCostRegLineIGrid.opeTime'], 90, '', null),
    Column.text('HUM_PRE_TIME', Messages['MfgTotalCostRegLineIGrid.humPreTime'], 90, '', null),
    Column.text('HUM_ACT_TIME', Messages['MfgTotalCostRegLineIGrid.humActTime'], 90, '', null),
    Column.text('MAC_PRE_TIME', Messages['MfgTotalCostRegLineIGrid.macPreTime'], 90, '', null),
    Column.text('MAC_ACT_TIME', Messages['MfgTotalCostRegLineIGrid.macActTime'], 90, '', null),
    Column.text('SUM_UNIT_SUPPLY', Messages['MfgTotalCostRegLineIGrid.sumUnitSupply'], 100, '', null),
    Column.text('MATERIALS_COST', Messages['MfgTotalCostRegLineIGrid.materialsCost'], 90, '', null),
    Column.text('HUM_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineIGrid.humLaborCostFirst'], 90, '', null),
    Column.text('HUM_EXPENSES_FIRST', Messages['MfgTotalCostRegLineIGrid.humExpensesFirst'], 90, '', null),
    Column.text('HUM_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineIGrid.humLaborCostSecond'], 90, '', null),
    Column.text('HUM_EXPENSES_SECOND', Messages['MfgTotalCostRegLineIGrid.humExpensesSecond'], 90, '', null),
    Column.text('MAC_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineIGrid.macLaborCostFirst'], 90, '', null),
    Column.text('MAC_EXPENSES_FIRST', Messages['MfgTotalCostRegLineIGrid.macExpensesFirst'], 90, '', null),
    Column.text('MAC_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineIGrid.macLaborCostSecond'], 90, '', null),
    Column.text('MAC_EXPENSES_SECOND', Messages['MfgTotalCostRegLineIGrid.macExpensesSecond'], 90, '', null),
    Column.select('DATA_SOURCE_KBN', Messages['MfgTotalCostRegLineIGrid.dataSourceKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.cell('TIME_STAMP_CREATE', Messages['MfgTotalCostRegLineIGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MfgTotalCostRegLineIGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MfgTotalCostRegLineIGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MfgTotalCostRegLineIGrid.userIdChange'], 100, 'metaInfo', null),
    Column.text('GROSS_SUM_COST_FIRST', Messages['MfgTotalCostRegLineIGrid.grossSumCostFirst'], 90, '', null),
    Column.text('GROSS_SUM_COST_SECOND', Messages['MfgTotalCostRegLineIGrid.grossSumCostSecond'], 90, '', null),
    Column.text('TOTAL_GROSS_SUM_COST', Messages['MfgTotalCostRegLineIGrid.totalGrossSumCost'], 90, '', null),
    Column.text('GROSS_SUM_UNIT_SUPPLY', Messages['MfgTotalCostRegLineIGrid.grossSumUnitSupply'], 100, '', null),
];
