/**
 * MFG_TOTAL_COST_REG_LINE_M_Qグリッド定義
 */

let MfgTotalCostRegLineMQGridColumns = [
    Column.cell('YY', Messages['MfgTotalCostRegLineMQGrid.yy'], 40, 'primaryKey', null),
    Column.cell('PRO_GROUP_NO', Messages['MfgTotalCostRegLineMQGrid.proGroupNo'], 20, 'primaryKey', null),
    Column.cell('HINBAN', Messages['MfgTotalCostRegLineMQGrid.hinban'], 250, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MfgTotalCostRegLineMQGrid.routing'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MfgTotalCostRegLineMQGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.refer('SUP_CODE', Messages['MfgTotalCostRegLineMQGrid.supCode'], 60, '', 'SUP_NAME'),
    Column.text('OPE_DETAIL', Messages['MfgTotalCostRegLineMQGrid.opeDetail'], 100, '', null),
    Column.cell('MM', Messages['MfgTotalCostRegLineMQGrid.mm'], 20, 'primaryKey', null),
    Column.select('LAST_ROUTING_KBN', Messages['MfgTotalCostRegLineMQGrid.lastRoutingKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('TOTAL_COST_TARGET_FLAG', Messages['MfgTotalCostRegLineMQGrid.totalCostTargetFlag'], 10, ''),
    Column.select('COST_RATE_KBN', Messages['MfgTotalCostRegLineMQGrid.costRateKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('UNIT_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.unitCostFirst'], 90, '', null),
    Column.text('UNIT_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.unitCostSecond'], 90, '', null),
    Column.text('TOTAL_UNIT_COST', Messages['MfgTotalCostRegLineMQGrid.totalUnitCost'], 90, '', null),
    Column.text('SUM_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.sumCostFirst'], 90, '', null),
    Column.text('SUM_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.sumCostSecond'], 90, '', null),
    Column.text('TOTAL_SUM_COST', Messages['MfgTotalCostRegLineMQGrid.totalSumCost'], 90, '', null),
    Column.text('OPE_COUNTS', Messages['MfgTotalCostRegLineMQGrid.opeCounts'], 50, '', null),
    Column.text('OPE_AMOUNTS', Messages['MfgTotalCostRegLineMQGrid.opeAmounts'], 120, '', null),
    Column.text('UNIT_WEIGHT', Messages['MfgTotalCostRegLineMQGrid.unitWeight'], 110, '', null),
    Column.text('OPE_TIME', Messages['MfgTotalCostRegLineMQGrid.opeTime'], 90, '', null),
    Column.text('HUM_PRE_TIME', Messages['MfgTotalCostRegLineMQGrid.humPreTime'], 90, '', null),
    Column.text('HUM_ACT_TIME', Messages['MfgTotalCostRegLineMQGrid.humActTime'], 90, '', null),
    Column.text('MAC_PRE_TIME', Messages['MfgTotalCostRegLineMQGrid.macPreTime'], 90, '', null),
    Column.text('MAC_ACT_TIME', Messages['MfgTotalCostRegLineMQGrid.macActTime'], 90, '', null),
    Column.text('SUM_UNIT_SUPPLY', Messages['MfgTotalCostRegLineMQGrid.sumUnitSupply'], 100, '', null),
    Column.text('MATERIALS_COST', Messages['MfgTotalCostRegLineMQGrid.materialsCost'], 90, '', null),
    Column.text('HUM_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.humLaborCostFirst'], 90, '', null),
    Column.text('HUM_EXPENSES_FIRST', Messages['MfgTotalCostRegLineMQGrid.humExpensesFirst'], 90, '', null),
    Column.text('HUM_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.humLaborCostSecond'], 90, '', null),
    Column.text('HUM_EXPENSES_SECOND', Messages['MfgTotalCostRegLineMQGrid.humExpensesSecond'], 90, '', null),
    Column.text('MAC_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.macLaborCostFirst'], 90, '', null),
    Column.text('MAC_EXPENSES_FIRST', Messages['MfgTotalCostRegLineMQGrid.macExpensesFirst'], 90, '', null),
    Column.text('MAC_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.macLaborCostSecond'], 90, '', null),
    Column.text('MAC_EXPENSES_SECOND', Messages['MfgTotalCostRegLineMQGrid.macExpensesSecond'], 90, '', null),
    Column.select('DATA_SOURCE_KBN', Messages['MfgTotalCostRegLineMQGrid.dataSourceKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('T_UNIT_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.tUnitCostFirst'], 90, '', null),
    Column.text('T_UNIT_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.tUnitCostSecond'], 90, '', null),
    Column.text('T_TOTAL_UNIT_COST', Messages['MfgTotalCostRegLineMQGrid.tTotalUnitCost'], 90, '', null),
    Column.text('T_SUM_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.tSumCostFirst'], 90, '', null),
    Column.text('T_SUM_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.tSumCostSecond'], 90, '', null),
    Column.text('T_TOTAL_SUM_COST', Messages['MfgTotalCostRegLineMQGrid.tTotalSumCost'], 90, '', null),
    Column.text('T_OPE_COUNTS', Messages['MfgTotalCostRegLineMQGrid.tOpeCounts'], 30, '', null),
    Column.text('T_OPE_AMOUNTS', Messages['MfgTotalCostRegLineMQGrid.tOpeAmounts'], 110, '', null),
    Column.text('T_UNIT_WEIGHT', Messages['MfgTotalCostRegLineMQGrid.tUnitWeight'], 110, '', null),
    Column.text('T_OPE_TIME', Messages['MfgTotalCostRegLineMQGrid.tOpeTime'], 70, '', null),
    Column.text('T_HUM_PRE_TIME', Messages['MfgTotalCostRegLineMQGrid.tHumPreTime'], 70, '', null),
    Column.text('T_HUM_ACT_TIME', Messages['MfgTotalCostRegLineMQGrid.tHumActTime'], 70, '', null),
    Column.text('T_MAC_PRE_TIME', Messages['MfgTotalCostRegLineMQGrid.tMacPreTime'], 70, '', null),
    Column.text('T_MAC_ACT_TIME', Messages['MfgTotalCostRegLineMQGrid.tMacActTime'], 70, '', null),
    Column.text('T_SUM_UNIT_SUPPLY', Messages['MfgTotalCostRegLineMQGrid.tSumUnitSupply'], 100, '', null),
    Column.text('T_MATERIALS_COST', Messages['MfgTotalCostRegLineMQGrid.tMaterialsCost'], 90, '', null),
    Column.text('T_HUM_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.tHumLaborCostFirst'], 90, '', null),
    Column.text('T_HUM_EXPENSES_FIRST', Messages['MfgTotalCostRegLineMQGrid.tHumExpensesFirst'], 90, '', null),
    Column.text('T_HUM_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.tHumLaborCostSecond'], 90, '', null),
    Column.text('T_HUM_EXPENSES_SECOND', Messages['MfgTotalCostRegLineMQGrid.tHumExpensesSecond'], 90, '', null),
    Column.text('T_MAC_LABOR_COST_FIRST', Messages['MfgTotalCostRegLineMQGrid.tMacLaborCostFirst'], 90, '', null),
    Column.text('T_MAC_EXPENSES_FIRST', Messages['MfgTotalCostRegLineMQGrid.tMacExpensesFirst'], 90, '', null),
    Column.text('T_MAC_LABOR_COST_SECOND', Messages['MfgTotalCostRegLineMQGrid.tMacLaborCostSecond'], 90, '', null),
    Column.text('T_MAC_EXPENSES_SECOND', Messages['MfgTotalCostRegLineMQGrid.tMacExpensesSecond'], 90, '', null),
    Column.select('T_DATA_SOURCE_KBN', Messages['MfgTotalCostRegLineMQGrid.tDataSourceKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.cell('TIME_STAMP_CREATE', Messages['MfgTotalCostRegLineMQGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MfgTotalCostRegLineMQGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MfgTotalCostRegLineMQGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MfgTotalCostRegLineMQGrid.userIdChange'], 100, 'metaInfo', null),
];
