/**
 * MST_ROUTING_BKグリッド定義
 */

let MstRoutingBkGridColumns = [
    Column.cell('YY', Messages['MstRoutingBkGrid.yy'], 40, 'primaryKey', null),
    Column.refer('MAN_HINBAN', Messages['MstRoutingBkGrid.manHinban'], 250, 'primaryKey', 'MAN_HINMEI'),
    Column.cell('ROUTING_GROUP', Messages['MstRoutingBkGrid.routingGroup'], 20, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MstRoutingBkGrid.routing'], 20, 'primaryKey', null),
    Column.text('NECK_ROUTING', Messages['MstRoutingBkGrid.neckRouting'], 10, '', null),
    Column.text('OPE_DETAIL', Messages['MstRoutingBkGrid.opeDetail'], 100, '', null),
    Column.refer('WC_CODE', Messages['MstRoutingBkGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.text('HUM_PRE_TIME', Messages['MstRoutingBkGrid.humPreTime'], 70, '', null),
    Column.text('HUM_ACT_TIME', Messages['MstRoutingBkGrid.humActTime'], 70, '', null),
    Column.text('MAC_PRE_TIME', Messages['MstRoutingBkGrid.macPreTime'], 70, '', null),
    Column.text('MAC_ACT_TIME', Messages['MstRoutingBkGrid.macActTime'], 70, '', null),
    Column.text('COMMENT1', Messages['MstRoutingBkGrid.comment1'], 250, '', null),
    Column.text('COMMENT2', Messages['MstRoutingBkGrid.comment2'], 250, '', null),
    Column.text('LOT_SIZE', Messages['MstRoutingBkGrid.lotSize'], 60, '', null),
    Column.text('ACC_COUNTS', Messages['MstRoutingBkGrid.accCounts'], 60, '', null),
    Column.text('UNIT_WEIGHT', Messages['MstRoutingBkGrid.unitWeight'], 110, '', null),
    Column.select('STORE_KBN', Messages['MstRoutingBkGrid.storeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('STORE_NO', Messages['MstRoutingBkGrid.storeNo'], 100, '', null),
    Column.select('INSPECT_LANE_KBN', Messages['MstRoutingBkGrid.inspectLaneKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('INSPECT_KBN', Messages['MstRoutingBkGrid.inspectKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SUBINV_CODE', Messages['MstRoutingBkGrid.subinvCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('HUM_PRE_TIME_KBN', Messages['MstRoutingBkGrid.humPreTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('HUM_ACT_TIME_KBN', Messages['MstRoutingBkGrid.humActTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('MAC_PRE_TIME_KBN', Messages['MstRoutingBkGrid.macPreTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('MAC_ACT_TIME_KBN', Messages['MstRoutingBkGrid.macActTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('SUPPLY_FLAG', Messages['MstRoutingBkGrid.supplyFlag'], 10, ''),
    Column.cell('TIME_STAMP_CREATE', Messages['MstRoutingBkGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstRoutingBkGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstRoutingBkGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstRoutingBkGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('MUSHO_HACCHU_F', Messages['MstRoutingBkGrid.mushoHacchuF'], 10, ''),
];
