/**
 * MST_ROUTINGグリッド定義
 */

let MstRoutingGridColumns = [
    Column.refer('MAN_HINBAN', Messages['MstRoutingGrid.manHinban'], 250, 'primaryKey', 'MAN_HINMEI'),
    Column.cell('ROUTING_GROUP', Messages['MstRoutingGrid.routingGroup'], 20, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MstRoutingGrid.routing'], 20, 'primaryKey', null),
    Column.text('NECK_ROUTING', Messages['MstRoutingGrid.neckRouting'], 10, '', null),
    Column.text('OPE_DETAIL', Messages['MstRoutingGrid.opeDetail'], 100, '', null),
    Column.refer('WC_CODE', Messages['MstRoutingGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.text('HUM_PRE_TIME', Messages['MstRoutingGrid.humPreTime'], 70, '', null),
    Column.text('HUM_ACT_TIME', Messages['MstRoutingGrid.humActTime'], 70, '', null),
    Column.text('MAC_PRE_TIME', Messages['MstRoutingGrid.macPreTime'], 70, '', null),
    Column.text('MAC_ACT_TIME', Messages['MstRoutingGrid.macActTime'], 70, '', null),
    Column.text('COMMENT1', Messages['MstRoutingGrid.comment1'], 250, '', null),
    Column.text('COMMENT2', Messages['MstRoutingGrid.comment2'], 250, '', null),
    Column.text('LOT_SIZE', Messages['MstRoutingGrid.lotSize'], 60, '', null),
    Column.text('ACC_COUNTS', Messages['MstRoutingGrid.accCounts'], 60, '', null),
    Column.text('UNIT_WEIGHT', Messages['MstRoutingGrid.unitWeight'], 110, '', null),
    Column.select('STORE_KBN', Messages['MstRoutingGrid.storeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('STORE_NO', Messages['MstRoutingGrid.storeNo'], 100, '', null),
    Column.select('INSPECT_LANE_KBN', Messages['MstRoutingGrid.inspectLaneKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('INSPECT_KBN', Messages['MstRoutingGrid.inspectKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SUBINV_CODE', Messages['MstRoutingGrid.subinvCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('HUM_PRE_TIME_KBN', Messages['MstRoutingGrid.humPreTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('HUM_ACT_TIME_KBN', Messages['MstRoutingGrid.humActTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('MAC_PRE_TIME_KBN', Messages['MstRoutingGrid.macPreTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('MAC_ACT_TIME_KBN', Messages['MstRoutingGrid.macActTimeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('SUPPLY_FLAG', Messages['MstRoutingGrid.supplyFlag'], 10, ''),
    Column.cell('TIME_STAMP_CREATE', Messages['MstRoutingGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstRoutingGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstRoutingGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstRoutingGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('MUSHO_HACCHU_F', Messages['MstRoutingGrid.mushoHacchuF'], 10, ''),
    Column.select('TARGET_KBN', Messages['MstRoutingGrid.targetKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
];
