/**
 * MST_SUPPLIERグリッド定義
 */

let MstSupplierGridColumns = [
    Column.cell('SUP_CODE', Messages['MstSupplierGrid.supCode'], 60, 'primaryKey', null),
    Column.select('SUP_KBN', Messages['MstSupplierGrid.supKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SUP_NAME', Messages['MstSupplierGrid.supName'], 300, '', null),
    Column.text('SUP_RYAKU', Messages['MstSupplierGrid.supRyaku'], 200, '', null),
    Column.select('ZIP_CODE', Messages['MstSupplierGrid.zipCode'], 80, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('ADDRESS1', Messages['MstSupplierGrid.address1'], 300, '', null),
    Column.text('ADDRESS2', Messages['MstSupplierGrid.address2'], 300, '', null),
    Column.text('TEL_NO', Messages['MstSupplierGrid.telNo'], 140, '', null),
    Column.text('FAX_NO', Messages['MstSupplierGrid.faxNo'], 140, '', null),
    Column.text('DIV_NAME', Messages['MstSupplierGrid.divName'], 300, '', null),
    Column.text('SUP_OPE_NAME', Messages['MstSupplierGrid.supOpeName'], 300, '', null),
    Column.text('SUP_OPE_MAIL_ADD', Messages['MstSupplierGrid.supOpeMailAdd'], 300, '', null),
    Column.text('SUP_PERIOD_DAY', Messages['MstSupplierGrid.supPeriodDay'], 20, '', null),
    Column.text('PAY_DAY', Messages['MstSupplierGrid.payDay'], 20, '', null),
    Column.refer('TAX_CODE', Messages['MstSupplierGrid.taxCode'], 20, '', 'TAX_NAME'),
    Column.select('TAX_CAL_CODE', Messages['MstSupplierGrid.taxCalCode'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('TAX_DISP_CODE', Messages['MstSupplierGrid.taxDispCode'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('FRACTION_KBN', Messages['MstSupplierGrid.fractionKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('YOSHINGENDO', Messages['MstSupplierGrid.yoshingendo'], 110, '', null),
    Column.select('COMPANY_OPE_CODE', Messages['MstSupplierGrid.companyOpeCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('ORDER_ACCEPT_KBN', Messages['MstSupplierGrid.orderAcceptKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('LIST_OUTPUT_KBN', Messages['MstSupplierGrid.listOutputKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('PCH_COST_RATE_CODE', Messages['MstSupplierGrid.pchCostRateCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SEND_SUP_KBN', Messages['MstSupplierGrid.sendSupKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SEND_SUP_NAME', Messages['MstSupplierGrid.sendSupName'], 300, '', null),
    Column.text('SEND_SUP_RYAKU', Messages['MstSupplierGrid.sendSupRyaku'], 200, '', null),
    Column.select('SEND_ZIP_CODE', Messages['MstSupplierGrid.sendZipCode'], 80, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SEND_ADDRESS1', Messages['MstSupplierGrid.sendAddress1'], 300, '', null),
    Column.text('SEND_ADDRESS2', Messages['MstSupplierGrid.sendAddress2'], 300, '', null),
    Column.text('SEND_TEL_NO', Messages['MstSupplierGrid.sendTelNo'], 140, '', null),
    Column.text('SEND_FAX_NO', Messages['MstSupplierGrid.sendFaxNo'], 140, '', null),
    Column.text('SEND_INSPECT_LIST', Messages['MstSupplierGrid.sendInspectList'], 10, '', null),
    Column.text('COMPANY_DIV_NAME', Messages['MstSupplierGrid.companyDivName'], 300, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MstSupplierGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstSupplierGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstSupplierGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstSupplierGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('DELETE_FLAG', Messages['MstSupplierGrid.deleteFlag'], 10, ''),
    Column.text('NOHIN_YOBI_SUN', Messages['MstSupplierGrid.nohinYobiSun'], 10, '', null),
    Column.text('NOHIN_YOBI_MON', Messages['MstSupplierGrid.nohinYobiMon'], 10, '', null),
    Column.text('NOHIN_YOBI_TUE', Messages['MstSupplierGrid.nohinYobiTue'], 10, '', null),
    Column.text('NOHIN_YOBI_WED', Messages['MstSupplierGrid.nohinYobiWed'], 10, '', null),
    Column.text('NOHIN_YOBI_THU', Messages['MstSupplierGrid.nohinYobiThu'], 10, '', null),
    Column.text('NOHIN_YOBI_FRI', Messages['MstSupplierGrid.nohinYobiFri'], 10, '', null),
    Column.text('NOHIN_YOBI_SAT', Messages['MstSupplierGrid.nohinYobiSat'], 10, '', null),
    Column.select('NOHIN_SEND_YOHI_KBN', Messages['MstSupplierGrid.nohinSendYohiKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('BUNKATSU_MAIL_F', Messages['MstSupplierGrid.bunkatsuMailF'], 10, ''),
    Column.check('CHUMON_MAIL_F', Messages['MstSupplierGrid.chumonMailF'], 10, ''),
    Column.time('CHUMON_MAIL_HM', Messages['MstSupplierGrid.chumonMailHm'], 50, '', null),
    Column.check('KENSHU_MAIL_F', Messages['MstSupplierGrid.kenshuMailF'], 10, ''),
    Column.time('KENSHU_MAIL_HM', Messages['MstSupplierGrid.kenshuMailHm'], 50, '', null),
    Column.check('MAIL_BCC_F', Messages['MstSupplierGrid.mailBccF'], 10, ''),
];
