/**
 * MST_SUPPLIER_BKグリッド定義
 */

let MstSupplierBkGridColumns = [
    Column.cell('YY', Messages['MstSupplierBkGrid.yy'], 40, 'primaryKey', null),
    Column.cell('SUP_CODE', Messages['MstSupplierBkGrid.supCode'], 60, 'primaryKey', null),
    Column.select('SUP_KBN', Messages['MstSupplierBkGrid.supKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SUP_NAME', Messages['MstSupplierBkGrid.supName'], 300, '', null),
    Column.text('SUP_RYAKU', Messages['MstSupplierBkGrid.supRyaku'], 200, '', null),
    Column.select('ZIP_CODE', Messages['MstSupplierBkGrid.zipCode'], 80, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('ADDRESS1', Messages['MstSupplierBkGrid.address1'], 300, '', null),
    Column.text('ADDRESS2', Messages['MstSupplierBkGrid.address2'], 300, '', null),
    Column.text('TEL_NO', Messages['MstSupplierBkGrid.telNo'], 140, '', null),
    Column.text('FAX_NO', Messages['MstSupplierBkGrid.faxNo'], 140, '', null),
    Column.text('DIV_NAME', Messages['MstSupplierBkGrid.divName'], 300, '', null),
    Column.text('SUP_OPE_NAME', Messages['MstSupplierBkGrid.supOpeName'], 300, '', null),
    Column.text('SUP_OPE_MAIL_ADD', Messages['MstSupplierBkGrid.supOpeMailAdd'], 300, '', null),
    Column.text('SUP_PERIOD_DAY', Messages['MstSupplierBkGrid.supPeriodDay'], 20, '', null),
    Column.text('PAY_DAY', Messages['MstSupplierBkGrid.payDay'], 20, '', null),
    Column.refer('TAX_CODE', Messages['MstSupplierBkGrid.taxCode'], 20, '', 'TAX_NAME'),
    Column.select('TAX_CAL_CODE', Messages['MstSupplierBkGrid.taxCalCode'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('TAX_DISP_CODE', Messages['MstSupplierBkGrid.taxDispCode'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('FRACTION_KBN', Messages['MstSupplierBkGrid.fractionKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('YOSHINGENDO', Messages['MstSupplierBkGrid.yoshingendo'], 110, '', null),
    Column.select('COMPANY_OPE_CODE', Messages['MstSupplierBkGrid.companyOpeCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('ORDER_ACCEPT_KBN', Messages['MstSupplierBkGrid.orderAcceptKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('LIST_OUTPUT_KBN', Messages['MstSupplierBkGrid.listOutputKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('PCH_COST_RATE_CODE', Messages['MstSupplierBkGrid.pchCostRateCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SEND_SUP_KBN', Messages['MstSupplierBkGrid.sendSupKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SEND_SUP_NAME', Messages['MstSupplierBkGrid.sendSupName'], 300, '', null),
    Column.text('SEND_SUP_RYAKU', Messages['MstSupplierBkGrid.sendSupRyaku'], 200, '', null),
    Column.select('SEND_ZIP_CODE', Messages['MstSupplierBkGrid.sendZipCode'], 80, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('SEND_ADDRESS1', Messages['MstSupplierBkGrid.sendAddress1'], 300, '', null),
    Column.text('SEND_ADDRESS2', Messages['MstSupplierBkGrid.sendAddress2'], 300, '', null),
    Column.text('SEND_TEL_NO', Messages['MstSupplierBkGrid.sendTelNo'], 140, '', null),
    Column.text('SEND_FAX_NO', Messages['MstSupplierBkGrid.sendFaxNo'], 140, '', null),
    Column.text('SEND_INSPECT_LIST', Messages['MstSupplierBkGrid.sendInspectList'], 10, '', null),
    Column.text('COMPANY_DIV_NAME', Messages['MstSupplierBkGrid.companyDivName'], 300, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MstSupplierBkGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstSupplierBkGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstSupplierBkGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstSupplierBkGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('DELETE_FLAG', Messages['MstSupplierBkGrid.deleteFlag'], 10, ''),
    Column.text('NOHIN_YOBI_SUN', Messages['MstSupplierBkGrid.nohinYobiSun'], 10, '', null),
    Column.text('NOHIN_YOBI_MON', Messages['MstSupplierBkGrid.nohinYobiMon'], 10, '', null),
    Column.text('NOHIN_YOBI_TUE', Messages['MstSupplierBkGrid.nohinYobiTue'], 10, '', null),
    Column.text('NOHIN_YOBI_WED', Messages['MstSupplierBkGrid.nohinYobiWed'], 10, '', null),
    Column.text('NOHIN_YOBI_THU', Messages['MstSupplierBkGrid.nohinYobiThu'], 10, '', null),
    Column.text('NOHIN_YOBI_FRI', Messages['MstSupplierBkGrid.nohinYobiFri'], 10, '', null),
    Column.text('NOHIN_YOBI_SAT', Messages['MstSupplierBkGrid.nohinYobiSat'], 10, '', null),
    Column.select('NOHIN_SEND_YOHI_KBN', Messages['MstSupplierBkGrid.nohinSendYohiKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('BUNKATSU_MAIL_F', Messages['MstSupplierBkGrid.bunkatsuMailF'], 10, ''),
    Column.check('CHUMON_MAIL_F', Messages['MstSupplierBkGrid.chumonMailF'], 10, ''),
    Column.time('CHUMON_MAIL_HM', Messages['MstSupplierBkGrid.chumonMailHm'], 50, '', null),
    Column.check('KENSHU_MAIL_F', Messages['MstSupplierBkGrid.kenshuMailF'], 10, ''),
    Column.time('KENSHU_MAIL_HM', Messages['MstSupplierBkGrid.kenshuMailHm'], 50, '', null),
    Column.check('MAIL_BCC_F', Messages['MstSupplierBkGrid.mailBccF'], 10, ''),
];
