/**
 * MST_TOTAL_COST_REG_LINE_Qグリッド定義
 */

let MstTotalCostRegLineQGridColumns = [
    Column.cell('PRO_GROUP_NO', Messages['MstTotalCostRegLineQGrid.proGroupNo'], 20, 'primaryKey', null),
    Column.cell('HINBAN', Messages['MstTotalCostRegLineQGrid.hinban'], 250, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MstTotalCostRegLineQGrid.routing'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MstTotalCostRegLineQGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.refer('SUP_CODE', Messages['MstTotalCostRegLineQGrid.supCode'], 60, '', 'SUP_NAME'),
    Column.text('OPE_DETAIL', Messages['MstTotalCostRegLineQGrid.opeDetail'], 100, '', null),
    Column.select('LAST_ROUTING_KBN', Messages['MstTotalCostRegLineQGrid.lastRoutingKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('TOTAL_COST_TARGET_FLAG', Messages['MstTotalCostRegLineQGrid.totalCostTargetFlag'], 10, ''),
    Column.select('COST_RATE_KBN', Messages['MstTotalCostRegLineQGrid.costRateKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('UNIT_COST_FIRST', Messages['MstTotalCostRegLineQGrid.unitCostFirst'], 90, '', null),
    Column.text('UNIT_COST_SECOND', Messages['MstTotalCostRegLineQGrid.unitCostSecond'], 90, '', null),
    Column.text('TOTAL_UNIT_COST', Messages['MstTotalCostRegLineQGrid.totalUnitCost'], 90, '', null),
    Column.text('SUM_COST_FIRST', Messages['MstTotalCostRegLineQGrid.sumCostFirst'], 90, '', null),
    Column.text('SUM_COST_SECOND', Messages['MstTotalCostRegLineQGrid.sumCostSecond'], 90, '', null),
    Column.text('TOTAL_SUM_COST', Messages['MstTotalCostRegLineQGrid.totalSumCost'], 90, '', null),
    Column.text('OPE_COUNTS', Messages['MstTotalCostRegLineQGrid.opeCounts'], 50, '', null),
    Column.text('OPE_AMOUNTS', Messages['MstTotalCostRegLineQGrid.opeAmounts'], 120, '', null),
    Column.text('UNIT_WEIGHT', Messages['MstTotalCostRegLineQGrid.unitWeight'], 110, '', null),
    Column.text('OPE_TIME', Messages['MstTotalCostRegLineQGrid.opeTime'], 90, '', null),
    Column.text('HUM_PRE_TIME', Messages['MstTotalCostRegLineQGrid.humPreTime'], 90, '', null),
    Column.text('HUM_ACT_TIME', Messages['MstTotalCostRegLineQGrid.humActTime'], 90, '', null),
    Column.text('MAC_PRE_TIME', Messages['MstTotalCostRegLineQGrid.macPreTime'], 90, '', null),
    Column.text('MAC_ACT_TIME', Messages['MstTotalCostRegLineQGrid.macActTime'], 90, '', null),
    Column.text('SUM_UNIT_SUPPLY', Messages['MstTotalCostRegLineQGrid.sumUnitSupply'], 100, '', null),
    Column.text('MATERIALS_COST', Messages['MstTotalCostRegLineQGrid.materialsCost'], 90, '', null),
    Column.text('HUM_LABOR_COST_FIRST', Messages['MstTotalCostRegLineQGrid.humLaborCostFirst'], 90, '', null),
    Column.text('HUM_EXPENSES_FIRST', Messages['MstTotalCostRegLineQGrid.humExpensesFirst'], 90, '', null),
    Column.text('HUM_LABOR_COST_SECOND', Messages['MstTotalCostRegLineQGrid.humLaborCostSecond'], 90, '', null),
    Column.text('HUM_EXPENSES_SECOND', Messages['MstTotalCostRegLineQGrid.humExpensesSecond'], 90, '', null),
    Column.text('MAC_LABOR_COST_FIRST', Messages['MstTotalCostRegLineQGrid.macLaborCostFirst'], 90, '', null),
    Column.text('MAC_EXPENSES_FIRST', Messages['MstTotalCostRegLineQGrid.macExpensesFirst'], 90, '', null),
    Column.text('MAC_LABOR_COST_SECOND', Messages['MstTotalCostRegLineQGrid.macLaborCostSecond'], 90, '', null),
    Column.text('MAC_EXPENSES_SECOND', Messages['MstTotalCostRegLineQGrid.macExpensesSecond'], 90, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MstTotalCostRegLineQGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstTotalCostRegLineQGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstTotalCostRegLineQGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstTotalCostRegLineQGrid.userIdChange'], 100, 'metaInfo', null),
];
