/**
 * MST_TOTAL_COST_REG_LINE_BKグリッド定義
 */

let MstTotalCostRegLineBkGridColumns = [
    Column.cell('YY', Messages['MstTotalCostRegLineBkGrid.yy'], 40, 'primaryKey', null),
    Column.cell('HINBAN', Messages['MstTotalCostRegLineBkGrid.hinban'], 250, 'primaryKey', null),
    Column.cell('PRO_GROUP_NO', Messages['MstTotalCostRegLineBkGrid.proGroupNo'], 20, 'primaryKey', null),
    Column.cell('ROUTING', Messages['MstTotalCostRegLineBkGrid.routing'], 20, 'primaryKey', null),
    Column.refer('WC_CODE', Messages['MstTotalCostRegLineBkGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.refer('SUP_CODE', Messages['MstTotalCostRegLineBkGrid.supCode'], 60, '', 'SUP_NAME'),
    Column.text('OPE_DETAIL', Messages['MstTotalCostRegLineBkGrid.opeDetail'], 100, '', null),
    Column.select('LAST_ROUTING_KBN', Messages['MstTotalCostRegLineBkGrid.lastRoutingKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('TOTAL_COST_TARGET_FLAG', Messages['MstTotalCostRegLineBkGrid.totalCostTargetFlag'], 10, ''),
    Column.select('COST_RATE_KBN', Messages['MstTotalCostRegLineBkGrid.costRateKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('UNIT_COST_FIRST', Messages['MstTotalCostRegLineBkGrid.unitCostFirst'], 90, '', null),
    Column.text('UNIT_COST_SECOND', Messages['MstTotalCostRegLineBkGrid.unitCostSecond'], 90, '', null),
    Column.text('TOTAL_UNIT_COST', Messages['MstTotalCostRegLineBkGrid.totalUnitCost'], 90, '', null),
    Column.text('SUM_COST_FIRST', Messages['MstTotalCostRegLineBkGrid.sumCostFirst'], 90, '', null),
    Column.text('SUM_COST_SECOND', Messages['MstTotalCostRegLineBkGrid.sumCostSecond'], 90, '', null),
    Column.text('TOTAL_SUM_COST', Messages['MstTotalCostRegLineBkGrid.totalSumCost'], 90, '', null),
    Column.text('OPE_COUNTS', Messages['MstTotalCostRegLineBkGrid.opeCounts'], 50, '', null),
    Column.text('OPE_AMOUNTS', Messages['MstTotalCostRegLineBkGrid.opeAmounts'], 120, '', null),
    Column.text('UNIT_WEIGHT', Messages['MstTotalCostRegLineBkGrid.unitWeight'], 110, '', null),
    Column.text('OPE_TIME', Messages['MstTotalCostRegLineBkGrid.opeTime'], 90, '', null),
    Column.text('HUM_PRE_TIME', Messages['MstTotalCostRegLineBkGrid.humPreTime'], 90, '', null),
    Column.text('HUM_ACT_TIME', Messages['MstTotalCostRegLineBkGrid.humActTime'], 90, '', null),
    Column.text('MAC_PRE_TIME', Messages['MstTotalCostRegLineBkGrid.macPreTime'], 90, '', null),
    Column.text('MAC_ACT_TIME', Messages['MstTotalCostRegLineBkGrid.macActTime'], 90, '', null),
    Column.text('SUM_UNIT_SUPPLY', Messages['MstTotalCostRegLineBkGrid.sumUnitSupply'], 100, '', null),
    Column.text('MATERIALS_COST', Messages['MstTotalCostRegLineBkGrid.materialsCost'], 90, '', null),
    Column.text('HUM_LABOR_COST_FIRST', Messages['MstTotalCostRegLineBkGrid.humLaborCostFirst'], 90, '', null),
    Column.text('HUM_EXPENSES_FIRST', Messages['MstTotalCostRegLineBkGrid.humExpensesFirst'], 90, '', null),
    Column.text('HUM_LABOR_COST_SECOND', Messages['MstTotalCostRegLineBkGrid.humLaborCostSecond'], 90, '', null),
    Column.text('HUM_EXPENSES_SECOND', Messages['MstTotalCostRegLineBkGrid.humExpensesSecond'], 90, '', null),
    Column.text('MAC_LABOR_COST_FIRST', Messages['MstTotalCostRegLineBkGrid.macLaborCostFirst'], 90, '', null),
    Column.text('MAC_EXPENSES_FIRST', Messages['MstTotalCostRegLineBkGrid.macExpensesFirst'], 90, '', null),
    Column.text('MAC_LABOR_COST_SECOND', Messages['MstTotalCostRegLineBkGrid.macLaborCostSecond'], 90, '', null),
    Column.text('MAC_EXPENSES_SECOND', Messages['MstTotalCostRegLineBkGrid.macExpensesSecond'], 90, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['MstTotalCostRegLineBkGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['MstTotalCostRegLineBkGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['MstTotalCostRegLineBkGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['MstTotalCostRegLineBkGrid.userIdChange'], 100, 'metaInfo', null),
    Column.text('GROSS_SUM_COST_FIRST', Messages['MstTotalCostRegLineBkGrid.grossSumCostFirst'], 90, '', null),
    Column.text('GROSS_SUM_COST_SECOND', Messages['MstTotalCostRegLineBkGrid.grossSumCostSecond'], 90, '', null),
    Column.text('TOTAL_GROSS_SUM_COST', Messages['MstTotalCostRegLineBkGrid.totalGrossSumCost'], 90, '', null),
    Column.text('GROSS_SUM_UNIT_SUPPLY', Messages['MstTotalCostRegLineBkGrid.grossSumUnitSupply'], 100, '', null),
];
