/**
 * 得意先マスタグリッド定義
 */

let MTokuiGridColumns = [
    Column.cell('TOKUCD', Messages['MTokuiGrid.tokucd'], 80, 'primaryKey', null),
    Column.text('TOKUMEI1', Messages['MTokuiGrid.tokumei1'], 280, '', null),
    Column.text('TOKUMEI2', Messages['MTokuiGrid.tokumei2'], 220, '', null),
    Column.text('RTOKUMEI', Messages['MTokuiGrid.rtokumei'], 200, '', null),
    Column.text('UBINNO', Messages['MTokuiGrid.ubinno'], 80, '', null),
    Column.text('TOKU-JUSHO1', Messages['MTokuiGrid.tokuJusho1'], 280, '', null),
    Column.text('TOKU-JUSHO2', Messages['MTokuiGrid.tokuJusho2'], 220, '', null),
    Column.text('TELNO', Messages['MTokuiGrid.telno'], 120, '', null),
    Column.text('SEIKYUCD', Messages['MTokuiGrid.seikyucd'], 80, '', null),
    Column.text('MAILCD', Messages['MTokuiGrid.mailcd'], 80, '', null),
    Column.text('SHUKINCD', Messages['MTokuiGrid.shukincd'], 80, '', null),
    Column.text('HONSHACD', Messages['MTokuiGrid.honshacd'], 80, '', null),
    Column.text('SHUKEICD', Messages['MTokuiGrid.shukeicd'], 80, '', null),
    Column.select('TANKAKBN', Messages['MTokuiGrid.tankakbn'], 20, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('BONUSKBN', Messages['MTokuiGrid.bonuskbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('NOHINKBN', Messages['MTokuiGrid.nohinkbn'], 20, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('HAKKOKBN', Messages['MTokuiGrid.hakkokbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('NOHINFORMKBN', Messages['MTokuiGrid.nohinformkbn'], 30, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SIMUKEKBN', Messages['MTokuiGrid.simukekbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('EIGYOKBN', Messages['MTokuiGrid.eigyokbn'], 20, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('FILLER1', Messages['MTokuiGrid.filler1'], 10, '', null),
    Column.select('KINLESSKBN', Messages['MTokuiGrid.kinlesskbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SEIKYOKBN', Messages['MTokuiGrid.seikyokbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.date('TIKUSIMEBI', Messages['MTokuiGrid.tikusimebi'], 20, '', null),
    Column.date('MISESIMEBI', Messages['MTokuiGrid.misesimebi'], 20, '', null),
    Column.date('TOUROKUBI', Messages['MTokuiGrid.tourokubi'], 80, '', null),
    Column.select('JUKINKBN', Messages['MTokuiGrid.jukinkbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('TENKINKBN', Messages['MTokuiGrid.tenkinkbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('URISUMKBN', Messages['MTokuiGrid.urisumkbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('DIYKBN', Messages['MTokuiGrid.diykbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('KTOKUMEI', Messages['MTokuiGrid.ktokumei'], 200, '', null),
    Column.select('ZEIKBN', Messages['MTokuiGrid.zeikbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('EI-TANTOCD', Messages['MTokuiGrid.eiTantocd'], 40, '', null),
    Column.text('SICHOCD', Messages['MTokuiGrid.sichocd'], 60, '', null),
    Column.text('FAXNO', Messages['MTokuiGrid.faxno'], 120, '', null),
    Column.text('TOKUIKBN1', Messages['MTokuiGrid.tokuikbn1'], 20, '', null),
    Column.text('TOKUIKBN2', Messages['MTokuiGrid.tokuikbn2'], 20, '', null),
    Column.text('TOKUIKBN3', Messages['MTokuiGrid.tokuikbn3'], 20, '', null),
    Column.select('FAXKBN', Messages['MTokuiGrid.faxkbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('UNSOCD', Messages['MTokuiGrid.unsocd'], 30, '', null),
    Column.text('URISUMKBNM', Messages['MTokuiGrid.urisumkbnm'], 20, '', null),
    Column.text('TIKUCD', Messages['MTokuiGrid.tikucd'], 10, '', null),
    Column.text('TODOFUKENCD', Messages['MTokuiGrid.todofukencd'], 10, '', null),
    Column.text('KOKUSAICD', Messages['MTokuiGrid.kokusaicd'], 10, '', null),
    Column.text('KUNICD', Messages['MTokuiGrid.kunicd'], 20, '', null),
    Column.text('EIGYOAREACD', Messages['MTokuiGrid.eigyoareacd'], 10, '', null),
    Column.text('KENSYUKIKAN', Messages['MTokuiGrid.kensyukikan'], 20, '', null),
    Column.select('E-SEIKYUKBN', Messages['MTokuiGrid.eSeikyukbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('FILLER', Messages['MTokuiGrid.filler'], 170, '', null),
];
