/**
 * 有力店マスタグリッド定義
 */

let MYuryokuGridColumns = [
    Column.cell('YURYOCD', Messages['MYuryokuGrid.yuryocd'], 80, 'primaryKey', null),
    Column.text('RYURYOKUMEI', Messages['MYuryokuGrid.ryuryokumei'], 200, '', null),
    Column.text('YURYOMEI1', Messages['MYuryokuGrid.yuryomei1'], 280, '', null),
    Column.text('YURYOMEI2', Messages['MYuryokuGrid.yuryomei2'], 220, '', null),
    Column.text('YURYOKU-JUSHO1', Messages['MYuryokuGrid.yuryokuJusho1'], 280, '', null),
    Column.text('YURYOKU-JUSHO2', Messages['MYuryokuGrid.yuryokuJusho2'], 220, '', null),
    Column.text('UBINNO', Messages['MYuryokuGrid.ubinno'], 80, '', null),
    Column.text('TELNO', Messages['MYuryokuGrid.telno'], 120, '', null),
    Column.text('FAXNO', Messages['MYuryokuGrid.faxno'], 120, '', null),
    Column.text('YURYOKUKBN', Messages['MYuryokuGrid.yuryokukbn'], 10, '', null),
    Column.text('TOUROKUBI', Messages['MYuryokuGrid.tourokubi'], 80, '', null),
    Column.text('KYURYOKUMEI', Messages['MYuryokuGrid.kyuryokumei'], 200, '', null),
    Column.text('KI', Messages['MYuryokuGrid.ki'], 20, '', null),
    Column.text('KAMI-KONYU', Messages['MYuryokuGrid.kamiKonyu'], 90, '', null),
    Column.text('KAMI-SIHARAI', Messages['MYuryokuGrid.kamiSiharai'], 90, '', null),
    Column.text('KAMI-YUBORITU', Messages['MYuryokuGrid.kamiYuboritu'], 20, '', null),
    Column.text('KAMI-TASSEIKBN', Messages['MYuryokuGrid.kamiTasseikbn'], 10, '', null),
    Column.text('SIMO-KONYU', Messages['MYuryokuGrid.simoKonyu'], 90, '', null),
    Column.text('SIMO-SIHARAI', Messages['MYuryokuGrid.simoSiharai'], 90, '', null),
    Column.text('SIMO-YUBORITU', Messages['MYuryokuGrid.simoYuboritu'], 20, '', null),
    Column.text('SIMO-TASSEIKBN', Messages['MYuryokuGrid.simoTasseikbn'], 10, '', null),
    Column.text('YUTENKAIKBN', Messages['MYuryokuGrid.yutenkaikbn'], 10, '', null),
    Column.text('TORIHIKI-KBN', Messages['MYuryokuGrid.torihikiKbn'], 10, '', null),
    Column.text('GYOSHU-KBN', Messages['MYuryokuGrid.gyoshuKbn'], 20, '', null),
    Column.text('SICHOCD', Messages['MYuryokuGrid.sichocd'], 60, '', null),
    Column.text('FAXKBN', Messages['MYuryokuGrid.faxkbn'], 10, '', null),
    Column.text('RITUKBN', Messages['MYuryokuGrid.ritukbn'], 10, '', null),
    Column.text('UNSOCD', Messages['MYuryokuGrid.unsocd'], 30, '', null),
    Column.text('TIKUCD', Messages['MYuryokuGrid.tikucd'], 10, '', null),
    Column.text('TODOFUKENCD', Messages['MYuryokuGrid.todofukencd'], 10, '', null),
    Column.text('EIGYOKBN', Messages['MYuryokuGrid.eigyokbn'], 20, '', null),
    Column.text('YURYOKU-RANK', Messages['MYuryokuGrid.yuryokuRank'], 20, '', null),
    Column.text('STKBN', Messages['MYuryokuGrid.stkbn'], 10, '', null),
    Column.text('FILLER', Messages['MYuryokuGrid.filler'], 90, '', null),
];
