/**
 * PCH_ORDER_INFグリッド定義
 */

let PchOrderInfGridColumns = [
    Column.cell('ORDER_NO', Messages['PchOrderInfGrid.orderNo'], 100, 'primaryKey', null),
    Column.select('ORDER_KBN', Messages['PchOrderInfGrid.orderKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('ORDER_ID', Messages['PchOrderInfGrid.orderId'], 140, '', null),
    Column.select('ARRANGE_KBN', Messages['PchOrderInfGrid.arrangeKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('KANBAN_ID', Messages['PchOrderInfGrid.kanbanId'], 90, '', null),
    Column.text('SERIAL_NO', Messages['PchOrderInfGrid.serialNo'], 40, '', null),
    Column.text('ROUTING', Messages['PchOrderInfGrid.routing'], 20, '', null),
    Column.refer('WC_CODE', Messages['PchOrderInfGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.text('OPE_DETAIL', Messages['PchOrderInfGrid.opeDetail'], 100, '', null),
    Column.text('COMMENT1', Messages['PchOrderInfGrid.comment1'], 250, '', null),
    Column.text('COMMENT2', Messages['PchOrderInfGrid.comment2'], 250, '', null),
    Column.text('HINBAN', Messages['PchOrderInfGrid.hinban'], 250, '', null),
    Column.text('ORDER_COUNTS', Messages['PchOrderInfGrid.orderCounts'], 110, '', null),
    Column.refer('UNIT_CODE', Messages['PchOrderInfGrid.unitCode'], 20, '', 'UNIT_NAME'),
    Column.text('MEMO', Messages['PchOrderInfGrid.memo'], 300, '', null),
    Column.text('PERIOD', Messages['PchOrderInfGrid.period'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('PERIOD_CHG', Messages['PchOrderInfGrid.periodChg'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('ORDER_LT', Messages['PchOrderInfGrid.orderLt'], 90, '', null),
    Column.refer('SUP_CODE', Messages['PchOrderInfGrid.supCode'], 60, '', 'SUP_NAME'),
    Column.select('SUBINV_CODE', Messages['PchOrderInfGrid.subinvCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.select('SHIP_CODE', Messages['PchOrderInfGrid.shipCode'], 100, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('ORDER_UNIT', Messages['PchOrderInfGrid.orderUnit'], 90, '', null),
    Column.select('ACCEPT_KBN', Messages['PchOrderInfGrid.acceptKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('INSPECT_LANE', Messages['PchOrderInfGrid.inspectLane'], 10, '', null),
    Column.select('INSPECT_KBN', Messages['PchOrderInfGrid.inspectKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('REQUEST_REGIST', Messages['PchOrderInfGrid.requestRegist'], 100, '', null),
    Column.date('REQUEST_DATE', Messages['PchOrderInfGrid.requestDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('ORDER_REGIST', Messages['PchOrderInfGrid.orderRegist'], 100, '', null),
    Column.date('ORDER_DATE', Messages['PchOrderInfGrid.orderDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('ORDER_STATUS', Messages['PchOrderInfGrid.orderStatus'], 10, '', null),
    Column.date('ACCEPT_DATE', Messages['PchOrderInfGrid.acceptDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('ACCEPT_REGIST', Messages['PchOrderInfGrid.acceptRegist'], 100, '', null),
    Column.text('ACCEPT_COUNTS', Messages['PchOrderInfGrid.acceptCounts'], 110, '', null),
    Column.date('INSPECT_DATE', Messages['PchOrderInfGrid.inspectDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.text('INSPECT_REGIST', Messages['PchOrderInfGrid.inspectRegist'], 100, '', null),
    Column.text('INSPECT_COUNTS', Messages['PchOrderInfGrid.inspectCounts'], 110, '', null),
    Column.text('GOOD_COUNTS', Messages['PchOrderInfGrid.goodCounts'], 110, '', null),
    Column.text('REJECT_COUNTS', Messages['PchOrderInfGrid.rejectCounts'], 110, '', null),
    Column.text('INSPECT_UNIT', Messages['PchOrderInfGrid.inspectUnit'], 90, '', null),
    Column.text('REJECT_REASON', Messages['PchOrderInfGrid.rejectReason'], 30, '', null),
    Column.text('RETURN_REASON', Messages['PchOrderInfGrid.returnReason'], 30, '', null),
    Column.text('PERIOD_CHG_COUNTS', Messages['PchOrderInfGrid.periodChgCounts'], 20, '', null),
    Column.text('OUTPUT_STATUS', Messages['PchOrderInfGrid.outputStatus'], 10, '', null),
    Column.text('SHORT_NO', Messages['PchOrderInfGrid.shortNo'], 70, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['PchOrderInfGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['PchOrderInfGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['PchOrderInfGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['PchOrderInfGrid.userIdChange'], 100, 'metaInfo', null),
    Column.text('ORG_ORDER_UNIT', Messages['PchOrderInfGrid.orgOrderUnit'], 90, '', null),
    Column.check('MUSHO_HACCHU_F', Messages['PchOrderInfGrid.mushoHacchuF'], 10, ''),
    Column.longText('SUP_MEMO', Messages['PchOrderInfGrid.supMemo'], 300, '', null),
    Column.select('SHIHARAI_HOHO_KBN', Messages['PchOrderInfGrid.shiharaiHohoKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.check('ORDER_ISSHIKI_UNIT_F', Messages['PchOrderInfGrid.orderIsshikiUnitF'], 10, ''),
    Column.text('ORDER_ISSHIKI_COUNTS', Messages['PchOrderInfGrid.orderIsshikiCounts'], 110, '', null),
    Column.text('ORDER_ISSHIKI_UNIT', Messages['PchOrderInfGrid.orderIsshikiUnit'], 90, '', null),
    Column.check('INSPECT_ISSHIKI_UNIT_F', Messages['PchOrderInfGrid.inspectIsshikiUnitF'], 10, ''),
    Column.text('INSPECT_ISSHIKI_COUNTS', Messages['PchOrderInfGrid.inspectIsshikiCounts'], 110, '', null),
    Column.text('INSPECT_ISSHIKI_UNIT', Messages['PchOrderInfGrid.inspectIsshikiUnit'], 90, '', null),
    Column.text('ORG_BASE_ORDER_UNIT', Messages['PchOrderInfGrid.orgBaseOrderUnit'], 90, '', null),
    Column.text('ORG_MIN_ORDER_AMOUNT', Messages['PchOrderInfGrid.orgMinOrderAmount'], 110, '', null),
];
