/**
 * PRD_DAILY_PRO_PLAN_ARRグリッド定義
 */

let PrdDailyProPlanArrGridColumns = [
    Column.cell('PRO_NO', Messages['PrdDailyProPlanArrGrid.proNo'], 140, 'primaryKey', null),
    Column.text('CHILD_PLAN_NO', Messages['PrdDailyProPlanArrGrid.childPlanNo'], 120, '', null),
    Column.text('ROUTING', Messages['PrdDailyProPlanArrGrid.routing'], 20, '', null),
    Column.refer('WC_CODE', Messages['PrdDailyProPlanArrGrid.wcCode'], 30, '', 'WC_NAME'),
    Column.text('OPE_DETAIL', Messages['PrdDailyProPlanArrGrid.opeDetail'], 100, '', null),
    Column.select('MAC_LOAD_KBN', Messages['PrdDailyProPlanArrGrid.macLoadKbn'], 10, '', { json: 'MstCodeValueSearch.json', paramkey: 'code_nm', value: 'CODE_VALUE', label: 'CODE_VALUE_MEI' }),
    Column.text('HUM_PRE_TIME', Messages['PrdDailyProPlanArrGrid.humPreTime'], 70, '', null),
    Column.text('HUM_ACT_TIME', Messages['PrdDailyProPlanArrGrid.humActTime'], 70, '', null),
    Column.text('MAC_PRE_TIME', Messages['PrdDailyProPlanArrGrid.macPreTime'], 70, '', null),
    Column.text('MAC_ACT_TIME', Messages['PrdDailyProPlanArrGrid.macActTime'], 70, '', null),
    Column.text('COMMENT1', Messages['PrdDailyProPlanArrGrid.comment1'], 250, '', null),
    Column.text('COMMENT2', Messages['PrdDailyProPlanArrGrid.comment2'], 250, '', null),
    Column.text('UNIT_WEIGHT', Messages['PrdDailyProPlanArrGrid.unitWeight'], 110, '', null),
    Column.check('NECK_FLAG', Messages['PrdDailyProPlanArrGrid.neckFlag'], 10, ''),
    Column.text('NEXT_ROUT_PRO_NO', Messages['PrdDailyProPlanArrGrid.nextRoutProNo'], 140, '', null),
    Column.date('INITIAL_BEG_DATE', Messages['PrdDailyProPlanArrGrid.initialBegDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('INITIAL_END_DATE', Messages['PrdDailyProPlanArrGrid.initialEndDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('BEG_DATE', Messages['PrdDailyProPlanArrGrid.begDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('END_DATE', Messages['PrdDailyProPlanArrGrid.endDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('START_DATE', Messages['PrdDailyProPlanArrGrid.startDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.date('COMP_DATE', Messages['PrdDailyProPlanArrGrid.compDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.refer('OPE_WC_CODE', Messages['PrdDailyProPlanArrGrid.opeWcCode'], 30, '', 'OPE_WC_NAME'),
    Column.text('PRO_STATUS', Messages['PrdDailyProPlanArrGrid.proStatus'], 10, '', null),
    Column.date('DEL_CAN_DATE', Messages['PrdDailyProPlanArrGrid.delCanDate'], 70, '', Slick.Formatters.Extends.DateTime),
    Column.check('EXP_FLAG', Messages['PrdDailyProPlanArrGrid.expFlag'], 10, ''),
    Column.check('VISIBLE_FLAG', Messages['PrdDailyProPlanArrGrid.visibleFlag'], 10, ''),
    Column.check('SUP_FLAG', Messages['PrdDailyProPlanArrGrid.supFlag'], 10, ''),
    Column.text('SHORT_NO', Messages['PrdDailyProPlanArrGrid.shortNo'], 70, '', null),
    Column.cell('TIME_STAMP_CREATE', Messages['PrdDailyProPlanArrGrid.timeStampCreate'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('TIME_STAMP_CHANGE', Messages['PrdDailyProPlanArrGrid.timeStampChange'], 70, 'metaInfo', Slick.Formatters.Extends.DateTime),
    Column.cell('USER_ID_CREATE', Messages['PrdDailyProPlanArrGrid.userIdCreate'], 100, 'metaInfo', null),
    Column.cell('USER_ID_CHANGE', Messages['PrdDailyProPlanArrGrid.userIdChange'], 100, 'metaInfo', null),
    Column.check('DELETE_FLAG', Messages['PrdDailyProPlanArrGrid.deleteFlag'], 10, ''),
    Column.check('NYUKO_FLAG', Messages['PrdDailyProPlanArrGrid.nyukoFlag'], 20, ''),
];
